# -*- coding: utf-8 -*-
"""ml ass

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MdgResiATZaHcXJwgSQUvfh_MB6gCMEq
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

sns.set_style("whitegrid")

data = pd.DataFrame({
    'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'y': [2, 4, 5, 4, 5, 6, 7, 8, 9, 10],
    'category': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'value': [10, 15, 7, 9, 12, 14, 16, 18, 20, 22]
})

sns.scatterplot(x='x', y='y', hue='category', size='value', data=data)
plt.title("Scatter Plot Example")
plt.show()

sns.lineplot(x='x', y='y', hue='category', style='category', data=data)
plt.title("Line Plot Example")
plt.show()

sns.barplot(x='category', y='value', data=data)
plt.title("Bar Plot Example")
plt.show()

sns.boxplot(x='category', y='value', data=data)
plt.title("Box Plot Example")
plt.show()

sns.violinplot(x='category', y='value', data=data)
plt.title("Violin Plot Example")
plt.show()

sns.histplot(data=data, x='value', hue='category', bins=5, kde=True)
plt.title("Histogram Example")
plt.show()

sns.kdeplot(data=data, x='value', hue='category', shade=True)
plt.title("KDE Plot Example")
plt.show()

sns.pairplot(data=data, hue='category', diag_kind='kde')
plt.suptitle("Pair Plot Example", y=1.02)
plt.show()

corr = data[['x', 'y', 'value']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Heatmap Example")
plt.show()

sns.countplot(x='category', data=data)
plt.title("Count Plot Example")
plt.show()

tips = sns.load_dataset('tips')

sns.boxplot(x='day', y='total_bill', hue='sex', data=tips)
plt.title("Box Plot of Total Bill by Day and Sex")
plt.show()

import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'y': [2, 4, 5, 4, 5, 6, 7, 8, 9, 10],
    'category': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'value': [10, 15, 7, 9, 12, 14, 16, 18, 20, 22]
})

fig = px.scatter(data_frame=data, x='x', y='y', color='category', size='value', symbol='category', title="Scatter Plot Example")
fig.show()