# -*- coding: utf-8 -*-
"""ml ass

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1alX-eyO2TECHrDLtOrtVgyxyJyiIUJnZ
"""

import matplotlib.pyplot as plt
x = [1, 2, 3, 4]
y = [10, 20, 25, 30]
plt.plot(x, y, marker='o', linestyle='--', color='b')
plt.title('Line Plot')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.show()  # Or plt.savefig('line.png')

import matplotlib.pyplot as plt
x = [1, 2, 3, 4]
y = [10, 20, 25, 30]
plt.plot(x, y, marker='o', linestyle='--', color='b')
plt.title('Line Plot')
plt.xlabel('X Axis')
plt.ylabel('Y Axis')
plt.show()  # Or plt.savefig('line.png')

import plotly.express as px
import pandas as pd
df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [10, 20, 25, 30]})
fig = px.line(df, x='x', y='y', title='Line Plot', markers=True)
fig.show()  # Or fig.write_html('line.html')

import matplotlib.pyplot as plt
x = [1, 2, 3, 4]
y = [10, 20, 25, 30]
plt.scatter(x, y, color='r', s=50)
plt.title('Scatter Plot')
plt.show()

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
df = pd.DataFrame({'x': [1, 2, 3, 4], 'y': [10, 20, 25, 30]})
sns.scatterplot(x='x', y='y', data=df)
plt.title('Scatter Plot')
plt.show()

