# -*- coding: utf-8 -*-
"""ml ass

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iWOIhhX2rBsRiOMcpvnG3g4sntnFexJM
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    'Math': [78, 55, 88],
    'Science': [80, 60, 90],
    'English': [65, 72, 76],
    'Computer': [82, 58, 85]
}

df = pd.DataFrame(data)
corr = df.corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    'Category': ['Electronics', 'Clothing'],
    'Q1': [50, 30],
    'Q2': [60, 40],
    'Q3': [70, 35],
    'Q4': [120, 50]
}

df = pd.DataFrame(data).set_index('Category')
sns.heatmap(df, annot=True, cmap='YlOrRd')
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = {
    'State': ['Maharashtra', 'Kerala', 'Delhi', 'Karnataka', 'Tamil Nadu'],
    'Cases': [320, 250, 150, 180, 200]
}

df = pd.DataFrame(data).set_index('State')
sns.heatmap(df, annot=True, cmap='Reds', linewidths=0.5)
plt.title('COVID-19 Cases by State (in thousands)')
plt.show()

