# -*- coding: utf-8 -*-
"""Untitled6.ml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q_T_-8h1xZQv5EzZU_beoKcYY0pwdx82
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

sns.set_style("whitegrid")

data = pd.DataFrame({
    'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'y': [2, 4, 5, 4, 5, 6, 7, 8, 9, 10],
    'category': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'value': [10, 15, 7, 9, 12, 14, 16, 18, 20, 22]
})

sns.lineplot(x='x', y='y', hue='category', style='category', data=data)
plt.title("Line Plot Example")
plt.show()

sns.barplot(x='category', y='value', data=data)
plt.title("Bar Plot Example")
plt.show()

sns.boxplot(x='category', y='value', data=data)
plt.title("Box Plot Example")
plt.show()

sns.violinplot(x='category', y='value', data=data)
plt.title("Violin Plot Example")
plt.show()

sns.histplot(data=data, x='value', hue='category', bins=5, kde=True)
plt.title("Histogram Example")
plt.show()

sns.kdeplot(data=data, x='value', hue='category', shade=True)
plt.title("KDE Plot Example")
plt.show()

sns.pairplot(data=data, hue='category', diag_kind='kde')
plt.suptitle("Pair Plot Example", y=1.02)
plt.show()

corr = data[['x', 'y', 'value']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Heatmap Example")
plt.show()

sns.countplot(x='category', data=data)
plt.title("Count Plot Example")
plt.show()

tips = sns.load_dataset('tips')

sns.boxplot(x='day', y='total_bill', hue='sex', data=tips)
plt.title("Box Plot of Total Bill by Day and Sex")
plt.show()

sns.scatterplot(x='x', y='y', hue='category', size='value', data=data)
plt.title("Scatter Plot Example")
plt.show()

import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'x': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'y': [2, 4, 5, 4, 5, 6, 7, 8, 9, 10],
    'category': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'value': [10, 15, 7, 9, 12, 14, 16, 18, 20, 22]
})

fig = px.scatter(data_frame=data, x='x', y='y', color='category', size='value', symbol='category', title="Scatter Plot Example")
fig.show()

fig = px.line(data_frame=data, x='x', y='y', color='category', line_dash='category', title="Line Plot Example")
fig.show()

fig = px.bar(data_frame=data, x='category', y='value', color='category', title="Bar Plot Example", barmode='group')
fig.show()

# px.box(data_frame=df, x='column_x', y='column_y', color='column')
# - `x`, `y`: Columns for x and y axes (one often categorical).
# - `color`: Color boxes by a categorical variable.
fig = px.box(data_frame=data, x='category', y='value', color='category', title="Box Plot Example")
fig.show()

fig = px.violin(data_frame=data, x='category', y='value', color='category', box=True, title="Violin Plot Example")
fig.show()

# px.histogram(data_frame=df, x='column', color='column', nbins=n, marginal='rug')
# - `x`: Column to plot.
# - `color`: Color bars by a categorical variable.
# - `nbins`: Number of bins.
# - `marginal`: Add 'rug', 'box', or 'violin' to the plot margins.
fig = px.histogram(data_frame=data, x='value', color='category', title="Histogram Example")
fig.show()

fig = px.histogram(data_frame=data, x='value', color='category', nbins=5, title="Histogram Example", marginal='rug')
fig.show()

fig = px.density_contour(data_frame=data, x='x', y='y', color='category', title="Density Contour Plot Example")
fig.show()

fig = px.scatter_matrix(data_frame=data, dimensions=['x', 'y', 'value'], color='category', title="Pair Plot Example")
fig.show()

corr = data[['x', 'y', 'value']].corr()
fig = go.Figure(data=go.Heatmap(z=corr.values, x=corr.columns, y=corr.index, colorscale='Viridis', text=corr.values, texttemplate="%.2f"))
fig.update_layout(title="Heatmap Example")
fig.show()

fig = px.histogram(data_frame=data, x='category', color='category', title="Count Plot Example", barmode='group')
fig.show()