# -*- coding: utf-8 -*-
"""Untitled1.ml

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UAccwjEpGfbTIrkiGPS6jKiKrATYXKft

# New Section
"""

my_list = [1, 2, "hello", 4.5]
print(f"List: {my_list}")

my_tuple = (10, "world", 20)
print(f"Tuple: {my_tuple}")

my_dict = {"name": "Alice", "age": 30, "city": "New York"}
print(f"Dictionary: {my_dict}")

data = {
    "Name": ["John", "Anna", "Peter"],
    "Age": [28, 24, 35],
    "City": ["London", "Paris", "Berlin"]
}
df_from_dict = pd.DataFrame(data)
print("\nDataFrame from Dictionary:")
print(df_from_dict)

data_list = [
    ["John", 28, "London"],
    ["Anna", 24, "Paris"],
    ["Peter", 35, "Berlin"]
]
df_from_list = pd.DataFrame(data_list, columns=["Name", "Age", "City"])
print("\nDataFrame from List of Lists:")
print(df_from_list)